branch-defaults:
  default:
    environment: Ssr-api-dev2
  main:
    environment: Ssr-api-dev2
environment-defaults:
  Ssr-api-dev2:
    branch: null
    repository: null
global:
  application_name: ssr-api
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
